/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.getupfit;

import java.time.DayOfWeek;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author jacie_3u2efj7
 */
public class pantalla_Inicial extends javax.swing.JFrame {


    //NO MOVER NADA DE ESTO BBS
    public void asignarEmocionesPorDia(String[] emociones, JLabel[] labelsPorDia) {
        Map<String, String> mapaEmociones = new HashMap<>();
        mapaEmociones.put("feliz", "/feliz.png");
        mapaEmociones.put("triste", "/triste.png");
        mapaEmociones.put("enojado", "/enojado.png");
        mapaEmociones.put("neutro", "/neutro.png");

        for (int i = 0; i < emociones.length && i < labelsPorDia.length; i++) {
            String emocion = emociones[i];
            String url = mapaEmociones.getOrDefault(emocion, mapaEmociones.get("neutro"));
            ImageIcon icon = new ImageIcon(getClass().getResource(url)); 
            labelsPorDia[i].setIcon(icon);
        }
    }

    String[] emociones = {"neutro", "feliz", "neutro", "neutro", "neutro", "triste", "neutro"}; // <---------------------------

    public void cargarTablero() {
        JLabel[] labelsSemana = {
            lunesLabel, martesLabel, miercolesLabel,
            juevesLabel, viernesLabel, sabadoLabel, domingoLabel
        };

        //Este valor le cambia la carita
        //hay enojado, triste, feliz, neutro
        asignarEmocionesPorDia(emociones, labelsSemana);
    }

    public void actualizarEmocionDiaActual(String emocionNueva) {
        DayOfWeek dia = LocalDate.now().getDayOfWeek();
        int indexDia = dia.getValue() - 1; 

        emociones[indexDia] = emocionNueva;

        cargarTablero();
    }

    public pantalla_Inicial() {
        initComponents();
        cargarTablero(); 
        crearGraficaDeEstadosDeAnimo();
        this.setLocationRelativeTo(null);
    }
    
    
    //****************** grafica
    
        private void crearGraficaDeEstadosDeAnimo() {
       // Datos de emociones por día de la semana

       // Valores asignados a cada emoción
       int valorFeliz = 4;
       int valorEnojado = 3;
       int valorNeutro = 2;
       int valorTriste = 1;

       DefaultCategoryDataset dataset = new DefaultCategoryDataset();

       String[] dias = {"Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"};

       for (int i = 0; i < emociones.length; i++) {
           int valor;
           switch (emociones[i].toLowerCase()) {
               case "feliz":
                   valor = valorFeliz;
                   break;
               case "enojado":
                   valor = valorEnojado;
                   break;
               case "neutro":
                   valor = valorNeutro;
                   break;
               case "triste":
                   valor = valorTriste;
                   break;
               default:
                   valor = valorNeutro;
           }
           dataset.addValue(valor, "Estado de Ánimo", dias[i]);
       }

       // Crear gráfica de líneas
       JFreeChart chart = ChartFactory.createLineChart(
               "Estado de Ánimo por Día", // título
               "Día",                      // eje X
               "",                         // eje Y vacío
               dataset);

       // Personalizar la gráfica
       org.jfree.chart.plot.CategoryPlot plot = chart.getCategoryPlot();

       // Quitar números del eje Y
       plot.getRangeAxis().setTickLabelsVisible(false);
       plot.getRangeAxis().setTickMarksVisible(false);
       plot.getRangeAxis().setAxisLineVisible(false);

       // Cambiar color de la línea a azul
       org.jfree.chart.renderer.category.LineAndShapeRenderer renderer =
               (org.jfree.chart.renderer.category.LineAndShapeRenderer) plot.getRenderer();
       renderer.setSeriesPaint(0, new java.awt.Color(0, 102, 204)); // azul medio

       // Crear y agregar el panel
       ChartPanel chartPanel = new ChartPanel(chart);
       chartPanel.setPreferredSize(jPanel1.getSize());

       jPanel1.removeAll();
       jPanel1.setLayout(new java.awt.BorderLayout());
       jPanel1.add(chartPanel, java.awt.BorderLayout.CENTER);
       jPanel1.validate();
       jPanel1.repaint();
   }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lunesLabel = new javax.swing.JLabel();
        martesLabel = new javax.swing.JLabel();
        miercolesLabel = new javax.swing.JLabel();
        juevesLabel = new javax.swing.JLabel();
        viernesLabel = new javax.swing.JLabel();
        sabadoLabel = new javax.swing.JLabel();
        domingoLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(java.awt.SystemColor.textHighlight);

        jPanel4.setBackground(new java.awt.Color(219, 237, 254));
        jPanel4.setForeground(java.awt.SystemColor.textHighlight);

        lunesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neutro.png"))); // NOI18N

        martesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neutro.png"))); // NOI18N

        miercolesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neutro.png"))); // NOI18N

        juevesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neutro.png"))); // NOI18N

        viernesLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neutro.png"))); // NOI18N

        sabadoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neutro.png"))); // NOI18N

        domingoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neutro.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lunesLabel)
                .addGap(28, 28, 28)
                .addComponent(martesLabel)
                .addGap(31, 31, 31)
                .addComponent(miercolesLabel)
                .addGap(27, 27, 27)
                .addComponent(juevesLabel)
                .addGap(31, 31, 31)
                .addComponent(viernesLabel)
                .addGap(26, 26, 26)
                .addComponent(sabadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(domingoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(domingoLabel)
                    .addComponent(sabadoLabel)
                    .addComponent(viernesLabel)
                    .addComponent(juevesLabel)
                    .addComponent(miercolesLabel)
                    .addComponent(martesLabel)
                    .addComponent(lunesLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-peque.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dias.png"))); // NOI18N

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/barra.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iniciar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 384, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addComponent(jButton2)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jButton1)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new inicio_1().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
      
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String[] args) {
        new pantalla_Inicial().setVisible(true);
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel domingoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel juevesLabel;
    private javax.swing.JLabel lunesLabel;
    private javax.swing.JLabel martesLabel;
    private javax.swing.JLabel miercolesLabel;
    private javax.swing.JLabel sabadoLabel;
    private javax.swing.JLabel viernesLabel;
    // End of variables declaration//GEN-END:variables
}
